<?php
require_once __DIR__ . '/research-library.php';
$vertical = research_library()['verticals'][$vertical_slug];
$page = 'research';
$page_title = $vertical['name'] . ' — ManasAI';
$page_desc = $vertical['intro'];
include __DIR__ . '/header.php';
?>
<div class="container"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/research">Research</a><span aria-hidden="true">/</span><span><?= research_escape($vertical['name']) ?></span></nav></div>
<section class="container vertical-hero">
  <div><span class="eyebrow">Research vertical <?= research_escape($vertical['number']) ?> / ManasAI</span><h1><?= research_escape($vertical['heading']) ?><br><em><?= research_escape($vertical['emphasis']) ?></em></h1><p class="vertical-deck"><?= research_escape($vertical['deck']) ?></p><p><?= research_escape($vertical['intro']) ?></p><div class="research-tags"><?php foreach ($vertical['tags'] as $tag): ?><span><?= research_escape($tag) ?></span><?php endforeach; ?></div></div>
  <?php if ($vertical['graphic'] === 'devices'): include __DIR__ . '/device-visual.php'; else: include __DIR__ . '/research-visual.php'; endif; ?>
</section>
<div class="container"><?php include __DIR__ . '/vertical-navigation.php'; ?></div>
<section class="container section"><div class="editorial"><span class="eyebrow">The research question</span><h2><?= research_escape($vertical['question']) ?></h2><div><p class="lead"><?= research_escape($vertical['overview']) ?></p><?php if ($vertical_slug === 'devices'): ?><a href="/sakshisense#signals" class="text-link">See the SakshiSense signal scope ↗</a><?php endif; ?></div></div></section>
<?php if ($vertical_slug === 'consciousness-research'): ?>
<section class="container section section--compact" id="partner"><div class="research-partner"><div><span class="eyebrow">Consciousness research partner</span><span class="partner-wordmark">CPCSci<span>↗</span></span><p>Center for Philosophical<br>and Cognitive Sciences</p><span class="micro">Hosted by ISS Delhi</span></div><div><h2>A meeting point for<br><em>mind, matter, and meaning.</em></h2><p>CPCSci at the Institute for Science and Spirituality, Delhi brings philosophical, empirical, and computational inquiry together across cognition, consciousness, complex systems, and wellbeing.</p><p>Our partnership connects ManasAI’s applied research direction with this interdisciplinary setting for studying attention, awareness, and human experience.</p><a class="btn btn--primary" href="https://cpcsci.org/" target="_blank" rel="noopener">Explore CPCSci ↗</a></div></div></section>
<?php endif; ?>
<section class="dark-section"><div class="container section"><div class="section-heading"><div><span class="eyebrow">What we investigate</span><h2>Three connected<br><em>research directions.</em></h2></div><p>Questions guiding this vertical and its contribution to intelligence for inner wellbeing.</p></div><div class="grid grid--3"><?php foreach ($vertical['priorities'] as $i => [$title, $body]): ?><article class="card"><span class="card__tag">Direction 0<?= $i + 1 ?></span><h3><?= research_escape($title) ?></h3><p><?= research_escape($body) ?></p></article><?php endforeach; ?></div></div></section>
<section class="container section"><div class="section-heading"><div><span class="eyebrow">How we approach it</span><h2><?= research_escape($vertical['method_title']) ?></h2></div></div><div class="steps"><?php foreach ($vertical['methods'] as $i => [$title,$body]): ?><article><span>0<?= $i + 1 ?></span><h3><?= research_escape($title) ?></h3><p><?= research_escape($body) ?></p></article><?php endforeach; ?></div></section>
<section class="container section section--compact" id="publications"><div class="section-heading"><div><span class="eyebrow">Research that informs the direction</span><h2>Ideas with<br><em>a published trail.</em></h2></div><p>Selected work by our scientific lead and collaborators. Each paper is credited to its authors; publication status is shown alongside the source.</p></div><?php research_papers($vertical['papers']); ?><p class="section-footnote">These works inform the research agenda. They do not constitute validation of SakshiSense hardware or wellness outcomes.</p></section>
<section class="container section"><div class="editorial"><span class="eyebrow">Connection to inner wellbeing</span><h2><?= research_escape($vertical['connection_title']) ?></h2><div><p class="lead"><?= research_escape($vertical['connection']) ?></p><a href="/platform" class="text-link">Explore the wellness platform ↗</a></div></div></section>
<section class="container section section--compact"><div class="cta"><div><span class="eyebrow">Research with ManasAI</span><h2><?= research_escape($vertical['cta']) ?></h2><p><?= research_escape($vertical['cta_text']) ?></p></div><a class="btn btn--primary" href="<?= research_escape($vertical['cta_link']) ?>"><?= research_escape($vertical['cta_label']) ?> ↗</a></div><div class="related-verticals"><span class="eyebrow">Continue exploring</span><?php include __DIR__ . '/vertical-navigation.php'; ?></div></section>
<?php include __DIR__ . '/footer.php'; ?>
