<?php
$page = 'company';
$page_title = 'Company & team — ManasAI Technology Private Limited';
$page_desc = 'Meet ManasAI Technology Private Limited, the company developing research wearables and personalised wellness AI.';
include __DIR__ . '/partials/header.php';
?>
<section class="container page-intro"><span class="eyebrow">ManasAI Technology Private Limited</span><h1>Intelligence in service<br>of <em>inner wellbeing.</em></h1><p>We are a research-driven startup building instruments and AI systems to sense, model, and support the dynamics of mind. Our immediate focus is raw-signal wearables for labs developing personalised wellness models.</p></section>
<section class="container section section--compact"><div class="editorial"><span class="eyebrow">Why we’re building</span><h2>The person<br><em>behind the data.</em></h2><div><p class="lead">A useful model starts with a good question, a meaningful signal, and respect for the person it describes.</p><p>ManasAI brings together low-cost AI-powered devices, cutting-edge AI applications, consciousness-based research, and models for physical AI. We’re starting with stress and attention research, while keeping a wider commitment to the science of wellbeing.</p><p>Our aim is to give researchers better instruments and more room to develop models for individual needs.</p></div></div></section>
<section class="container section" id="team"><div class="section-heading"><div><span class="eyebrow">The team</span><h2>Researchers.<br>Engineers. <em>Builders.</em></h2></div><p>A small team connecting scientific questions with the work of building useful technology.</p></div><div class="people">
<article class="person"><img class="person__photo" src="/assets/img/team/jyotiranjan-beuria.jpeg" alt="Dr. Jyotiranjan Beuria" loading="lazy" width="360" height="360"><div class="person__body"><span class="person__role">Chief Scientist</span><h3>Dr. Jyotiranjan Beuria</h3><p>An alumnus of IIT Roorkee, HRI Prayagraj, and IIT Mandi, Dr. Beuria is a physicist by training. He leads ManasAI’s scientific direction across physics-informed AI, consciousness studies, and the integration of Indic knowledge systems with cognitive science.</p><p class="person__affil"><a href="mailto:jb@manasai.tech">jb@manasai.tech</a></p></div></article>
<article class="person"><img class="person__photo" src="/assets/img/team/rajat-garg.jpg" alt="Rajat Garg" loading="lazy" width="360" height="360"><div class="person__body"><span class="person__role">Chief Technology Officer</span><h3>Rajat Garg</h3><p>Rajat leads engineering at ManasAI, translating research into deployable systems. An IIT Roorkee and University of Minnesota graduate, he has built systems and AI products at Google, Amazon, and VMware.</p><p class="person__affil"><a href="mailto:rajat@manasai.tech">rajat@manasai.tech</a></p></div></article>
<article class="person"><img class="person__photo" src="/assets/img/team/akash-sharma.jpeg" alt="Akash Sharma" loading="lazy" width="360" height="360"><div class="person__body"><span class="person__role">Marketing &amp; Collaboration Head</span><h3>Akash Sharma</h3><p>Akash leads marketing and external collaboration at ManasAI, connecting our work with researchers and wellness organisations. His prior venture, HabitMantra, brings experience in the wellness sector.</p><p class="person__affil"><a href="mailto:akash@manasai.tech">akash@manasai.tech</a></p></div></article>
</div></section>
<section class="dark-section"><div class="container section"><div class="section-heading"><div><span class="eyebrow">Our commitments</span><h2>Rigour, with <em>restraint.</em></h2></div></div><div class="grid grid--3"><article class="card"><h3>Research first</h3><p>Define methods, test assumptions, and make claims that match the evidence.</p></article><article class="card"><h3>Consent &amp; privacy</h3><p>Plan collection, access, and retention with participants and study partners.</p></article><article class="card"><h3>Cultural rootedness</h3><p>Engage seriously with Indic traditions as sources of questions and frameworks.</p></article><article class="card"><h3>Accessibility</h3><p>Work towards affordable, practical instruments for research and wellness settings.</p></article><article class="card"><h3>Personal agency</h3><p>Design feedback that supports reflection and respects individual choice.</p></article><article class="card"><h3>Open inquiry</h3><p>Share methods and findings where consent, agreements, and research conditions allow.</p></article></div></div></section>
<section class="container section" id="partners"><div class="section-heading"><div><span class="eyebrow">Research &amp; engineering network</span><h2>Connected by <em>inquiry.</em></h2></div><p>Our collaborators and external affiliations support a wider exchange of ideas. ManasAI’s company identity and team are presented independently.</p></div><div class="collaborator-links"><a href="https://cpcsci.org/" target="_blank" rel="noopener">CPCSci at ISS Delhi · Consciousness research partner <span>↗</span></a><a href="https://krishnayanai.com/" target="_blank" rel="noopener">Krishnayan AI <span>↗</span></a></div></section>
<section class="container section section--compact" id="company-details"><div class="company-details"><span class="eyebrow">Company information</span><h2><?= htmlspecialchars($company['legal_name']) ?></h2><dl><div><dt>CIN</dt><dd><?= htmlspecialchars($company['cin']) ?></dd></div><div><dt>Registered office</dt><dd><?= htmlspecialchars($company['registered_office']) ?></dd></div><div><dt>Email</dt><dd><a href="mailto:admin@manasai.tech">admin@manasai.tech</a></dd></div></dl></div></section>
<?php include __DIR__ . '/partials/footer.php'; ?>
