<?php
$page = 'platform';
$page_title = 'Platform — From raw signals to personalised models | ManasAI';
$page_desc = 'A research platform in development: Sense, Infer, Guide, Learn. Raw wearable signals for personalised stress and attention models.';
include __DIR__ . '/partials/header.php';
?>
<section class="container page-intro"><span class="eyebrow">The platform / In development</span><h1>From raw signals<br>to <em>personal understanding.</em></h1><p>ManasAI is building a research-driven platform that connects wearable sensing with customised wellness models. Labs come first, followed by wellness centres working with defined research protocols.</p><a href="/contact?topic=Platform+collaboration" class="btn btn--primary">Discuss your workflow ↗</a></section>
<section class="container section section--compact"><div class="section-heading"><div><span class="eyebrow">The architecture</span><h2>Sense → Infer → Guide → Learn</h2></div><p>A development framework for turning observations into carefully evaluated, useful feedback.</p></div><div class="steps"><article><span>01 / INPUT</span><h3>Sense</h3><p>Capture raw wearable signals alongside task events and participant reports, using a consented study protocol.</p></article><article><span>02 / MODEL</span><h3>Infer</h3><p>Develop features and models, personalise against a baseline, and evaluate uncertainty and generalisation.</p></article><article><span>03 / FEEDBACK</span><h3>Guide</h3><p>Explore feedback with researchers and participants. Ground it in evidence and preserve individual choice.</p></article><article><span>04 / REFINEMENT</span><h3>Learn</h3><p>Use study findings to refine protocols, models, and hardware under agreed data-governance terms.</p></article></div></section>
<section class="dark-section" id="applications"><div class="container section"><div class="section-heading"><div><span class="eyebrow">Priority applications</span><h2>Two starting points.<br><em>Individual baselines.</em></h2></div><p>Wellness AI should account for differences between people, environments, and sessions. Our immediate focus is on the questions below.</p></div><div class="grid grid--2"><article class="card"><span class="card__tag">01 / Current focus</span><h3>Stress &amp; anxiety</h3><p>Investigate arousal and recovery using physiological signals, contextual events, and self-reports. Develop models that distinguish an individual’s patterns rather than assigning a universal stress score.</p></article><article class="card"><span class="card__tag">02 / Current focus</span><h3>Attention &amp; distraction</h3><p>Study focus, restlessness, and task disengagement using movement and physiological data alongside attention tasks and participant feedback. Evaluate what the signals can reliably tell us.</p></article></div><p class="section-footnote">Research applications, not diagnostic services. Performance must be established for the intended protocol and population.</p></div></section>
<section class="container section"><div class="section-heading"><div><span class="eyebrow">Technical direction</span><h2>A foundation you can<br><em>build on.</em></h2></div></div><div class="grid grid--2"><article class="card"><span class="card__tag">Signals</span><h3>Physiological AI</h3><p>Signal quality, artefact handling, and multimodal modelling, with physics-informed and physiology-aware approaches where appropriate.</p></article><article class="card"><span class="card__tag">Context</span><h3>Behavioural analytics</h3><p>Task annotations, reaction times, and self-reports to give physiological observations a meaningful study context.</p></article><article class="card"><span class="card__tag">Personalisation</span><h3>Custom models</h3><p>Research workflows for individual baselines and adaptation, with evaluation across participants and sessions.</p></article><article class="card"><span class="card__tag">Stewardship</span><h3>Research datasets</h3><p>Study-specific plans for consent, access, retention, and sharing. Data use and model-development rights should be agreed before collection.</p></article></div></section>
<section class="container section section--compact"><div class="section-heading"><div><span class="eyebrow">Longer-term research</span><h2>Room for the wider<br><em>science of wellbeing.</em></h2></div><p>These directions remain part of the vision. They are not separate products available for purchase.</p></div><div class="grid grid--3"><article class="card"><h3>Sleep &amp; recovery</h3><p>Investigating rhythm, routine, and recovery over time.</p></article><article class="card"><h3>Meditation</h3><p>Relating stillness, breath, and reported experience without grading the quality of practice.</p></article><article class="card"><h3>Reflective guidance</h3><p>Exploring culturally grounded retrieval and dialogue over Indic knowledge, with sources and evaluation.</p></article></div></section>
<section class="container section"><div class="cta"><div><span class="eyebrow">Your protocol, our starting point</span><h2>Build the study<br><em>before the score.</em></h2><p>Let’s define the data and evaluation your research needs.</p></div><a class="btn btn--primary" href="/contact?topic=Platform+collaboration">Talk to the team ↗</a></div></section>
<?php include __DIR__ . '/partials/footer.php'; ?>
