<?php
$page = 'research';
$page_title = 'Research — Intelligence for inner wellbeing | ManasAI';
$page_desc = 'Explore ManasAI’s four research verticals: low-cost AI-powered devices, cutting-edge AI applications, consciousness-based research, and models for physical AI.';
require_once __DIR__ . '/partials/research-library.php';
include __DIR__ . '/partials/header.php';
?>
<section class="container page-intro research-overview-intro"><span class="eyebrow">A research-driven startup</span><h1>Intelligence for<br><em>inner wellbeing.</em></h1><p class="mission-line">Grounded in signals. Guided by research.</p><p>ManasAI connects instruments, algorithms, human experience, and physical principles. Four complementary verticals turn that ambition into research questions, model development, and technology for personalised wellbeing.</p></section>
<section class="container section section--compact" id="verticals"><div class="research-hub-grid">
<?php $legacy_anchors = ['devices'=>'devices','ai-applications'=>'frontier','consciousness-research'=>'consciousness','physical-ai'=>'physics']; foreach (research_library()['verticals'] as $slug => $item): ?>
<article class="research-hub-card" id="<?= research_escape($legacy_anchors[$slug]) ?>"><span class="pillar-number">RESEARCH VERTICAL <?= research_escape($item['number']) ?> <span aria-hidden="true">↗</span></span><h2><a href="/<?= research_escape($slug) ?>"><?= research_escape($item['name']) ?></a></h2><p><?= research_escape($item['intro']) ?></p><div class="research-tags"><?php foreach ($item['tags'] as $tag): ?><span><?= research_escape($tag) ?></span><?php endforeach; ?></div><a href="/<?= research_escape($slug) ?>" class="text-link">Explore <?= research_escape($item['short']) ?> <span aria-hidden="true">↗</span></a></article>
<?php endforeach; ?>
</div></section>
<section class="dark-section"><div class="container section"><div class="section-heading"><div><span class="eyebrow">How the work comes together</span><h2>From fundamental questions<br>to <em>useful instruments.</em></h2></div><p>Our current product focus is SakshiSense: raw-signal wearables for personalised stress and attention research. Each vertical contributes a different part of that wider effort.</p></div><div class="steps"><article><span>01 / DEVICES</span><h3>Observe</h3><p>Make physiological and contextual signals accessible to researchers.</p></article><article><span>02 / APPLICATIONS</span><h3>Interpret</h3><p>Develop personalised models and evaluate their behaviour in context.</p></article><article><span>03 / CONSCIOUSNESS</span><h3>Understand</h3><p>Connect measurement with experience, meaning, and personal agency.</p></article><article><span>04 / PHYSICAL AI</span><h3>Model</h3><p>Investigate structured dynamics, memory, and computation over time.</p></article></div><a href="/sakshisense" class="text-link research-overview-cta">Meet SakshiSense ↗</a></div></section>
<section class="container section" id="publications"><div class="section-heading"><div><span class="eyebrow">Selected work</span><h2>A research direction<br><em>you can trace.</em></h2></div><p>These papers by our scientific lead and collaborators inform our work on contextual reasoning, representational ethics, and dynamical computation.</p></div><?php research_papers(['context','ethics','lindblad','chern'], true); ?><p class="research-footnote">Journal articles and preprints are identified separately. Author and institutional credits remain with the linked works; they are research foundations, not product-validation claims.</p></section>
<section class="container section section--compact"><div class="editorial"><span class="eyebrow">Consciousness research partner</span><h2>CPCSci<br><em>at ISS Delhi.</em></h2><div><p class="lead">The Center for Philosophical and Cognitive Sciences brings together research on cognition, consciousness, complex systems, and human wellbeing.</p><p>Explore the partnership within our consciousness-based research vertical.</p><a href="/consciousness-research#partner" class="text-link">Our consciousness research partnership ↗</a><br><a href="https://cpcsci.org/" target="_blank" rel="noopener" class="text-link">Visit CPCSci ↗</a></div></div></section>
<section class="container section"><div class="cta"><div><span class="eyebrow">Work with ManasAI</span><h2>Bring a question.<br><em>Build the evidence.</em></h2><p>Collaborate on instruments, AI applications, consciousness research, or the dynamics of computation.</p></div><a class="btn btn--primary" href="/contact?topic=Research+enquiry">Discuss a collaboration ↗</a></div></section>
<?php include __DIR__ . '/partials/footer.php'; ?>
