<?php
$page = 'sakshisense';
$page_title = 'SakshiSense — Research ring & wristband | ManasAI';
$page_desc = 'SakshiSense is a research wearable programme in development, targeting raw PPG, IMU, EDA and sound for customised wellness AI models.';
include __DIR__ . '/partials/header.php';
?>
<section class="container home-hero product-intro">
  <div><span class="eyebrow">SakshiSense / Research wearable programme</span><h1>Small form.<br><em>Open questions.</em></h1><p class="hero-sub">A ring and wristband platform for researchers who need the signal behind the summary.</p><p>We’re developing SakshiSense to stream raw physiological and contextual data for custom model development, starting with stress, anxiety, attention, and distraction.</p><div class="actions"><a class="btn btn--primary" href="/contact?topic=Research+kit">Enquire about a research kit ↗</a><a class="text-link" href="#signals">View signal scope ↓</a></div><div class="hero-status"><span class="status-dot"></span> Prototype programme · In development</div></div>
  <?php include __DIR__ . '/partials/device-visual.php'; ?>
</section>
<div class="container"><div class="notice"><strong>Research and wellness use.</strong> This generation is not a medical device or a consumer fitness ring. Enquiries help us scope research requirements; availability and specifications are confirmed directly.</div></div>
<section class="container section" id="signals">
  <div class="section-heading"><div><span class="eyebrow">The planned research kit</span><h2>Start at <em>the signal.</em></h2></div><p>Our target is raw-data access across four modalities. The table describes the programme’s scope, not a final specification for either form factor.</p></div>
  <div class="table-scroll"><table class="signal-table"><caption>Target signals and research uses</caption><thead><tr><th scope="col">Signal</th><th scope="col">What it captures</th><th scope="col">What you can investigate</th></tr></thead><tbody><tr><th scope="row">PPG <span>Photoplethysmography</span></th><td>Optical pulse waveforms</td><td>Pulse timing, variability, and physiological response</td></tr><tr><th scope="row">IMU <span>Inertial measurement</span></th><td>Movement and orientation signals</td><td>Activity context, stillness, and motion artefacts</td></tr><tr><th scope="row">EDA <span>Electrodermal activity</span></th><td>Changes in skin conductance</td><td>Arousal and recovery in the context of a study</td></tr><tr><th scope="row">Sound <span>Acoustic sensing</span></th><td>Audio captured with explicit consent</td><td>Study-defined acoustic context and sound features</td></tr></tbody></table></div>
  <p class="section-footnote">Sensor placement and combinations may differ between ring and wristband configurations. No sample rates, accuracy, battery life, or performance claims are being made at this stage.</p>
</section>
<section class="dark-section"><div class="container section"><?php include __DIR__ . '/partials/signal-explorer.php'; ?></div></section>
<section class="container section">
  <div class="section-heading"><div><span class="eyebrow">Built around your protocol</span><h2>The questions a lab<br><em>should be able to ask.</em></h2></div><p>Before a pilot, we’ll agree the hardware configuration, data requirements, and evaluation plan with your team.</p></div>
  <div class="grid grid--3"><article class="card"><span class="card__tag">01 / Capture</span><h3>Which signals, at what rate?</h3><p>Define modalities, sampling needs, session length, and signal-quality requirements. Final specifications depend on the research configuration.</p></article><article class="card"><span class="card__tag">02 / Access</span><h3>How will the data reach us?</h3><p>Discuss raw streaming, timestamp alignment, export formats, and integration with your tools. Connectivity, including BLE, is subject to configuration confirmation.</p></article><article class="card"><span class="card__tag">03 / Develop</span><h3>How will we personalise?</h3><p>Plan participant baselines, annotations, model training, and evaluation across people and sessions. Bring your own models or discuss collaboration.</p></article></div>
</section>
<section class="container section section--compact"><div class="editorial"><span class="eyebrow">Our design philosophy</span><h2>Wear it.<br><em>Forget it.</em></h2><div><p class="lead">An instrument should respect the experience it observes.</p><p>We aim for unobtrusive sensing, accessible hardware, and feedback that leaves the participant in control. SakshiSense takes its name from <em>sākṣī</em>, the witness: a reminder to observe carefully and interpret with restraint.</p><p>Meditation and contemplative practice remain part of our research direction, alongside our current work on stress and attention.</p></div></div></section>
<section class="container section"><div class="section-heading"><div><span class="eyebrow">A few practical answers</span><h2>Before you <em>begin.</em></h2></div></div><div class="faq">
  <details open><summary>Can I access raw data from the ring or wristband?</summary><p>Raw-signal streaming is central to the SakshiSense programme. Tell us which signals and export or streaming workflow your study needs; we’ll confirm the supported configuration and development status directly.</p></details>
  <details><summary>Can I buy a device today?</summary><p>SakshiSense is in development. We’re taking research enquiries, not online orders or payments. Research-batch availability, commercial terms, and timelines will be discussed once your requirements are understood.</p></details>
  <details><summary>Does every device include all four sensors?</summary><p>The programme targets PPG, IMU, EDA, and sound. The final sensor set may differ by form factor. We will confirm the actual configuration before any pilot or purchase.</p></details>
  <details><summary>Is there a subscription or a ready-to-use app?</summary><p>The intended commercial model combines research hardware with a separate annual subscription for data and model services. Scope and pricing are still being defined. A consumer app is not currently advertised as available.</p></details>
  <details><summary>Can it diagnose anxiety or measure attention directly?</summary><p>No. The purpose is research and wellness model development. Physiological signals need task context, participant reports, and validation; they are not a diagnosis or a direct measure of a person’s mental state.</p></details>
  <details><summary>How will sound capture and participant privacy be handled?</summary><p>Audio needs explicit consent and a study-specific collection plan. Discuss whether it is necessary, where processing will happen, who can access recordings, and how long they will be kept before a study begins.</p></details>
</div></section>
<section class="container section section--compact"><div class="cta"><div><span class="eyebrow">Bring your research question</span><h2>Let’s scope <em>your study.</em></h2><p>Share your required signals, participant count, and timeline.</p></div><a class="btn btn--primary" href="/contact?topic=Research+kit">Discuss a research kit ↗</a></div></section>
<?php include __DIR__ . '/partials/footer.php'; ?>
